# Change these first
owner: backbonecabal # Your GitHub username
repo: service-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Manifold Finance
    url: https://manifoldfinance.com
  - name: SushiSwap Exchange
    url: https://sushiswap.fi
  - name: SushiSwap GraphQL Endpoint
    url: https://github.com/sushiswap/sushiswap-subgraph
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /service-status
  logoUrl: https://rawcdn.githack.com/backbonecabal/static/0fd0978181197d12617d6a0b1d98e99e70e0c00b/backbonecabal_icon.png
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
